## Problem 1

In [4]:
import numpy as np

T = np.array([
    [0,1,-1],
    [-1,2,-4],
    [-2,3,-6],
    [-3,4,-7]
])

u = np.array([[1,-1,-1]])

v = np.matmul(T,u.transpose())

print(v)

[[0]
 [1]
 [1]
 [0]]


## problem 3

In [16]:
from sys import ps1
import numpy as np

T = np.array([
    [1,0,1,2],
    [1,1,0,1],
    [0,1,-1,-1]
])

#confirm correctness of t
e = np.array([[0,1,0,0]])
w = np.matmul(T,e.transpose())
print(w)

[[0]
 [1]
 [1]]


In [24]:

#confirm row echalon form
p1 = np.array([
    [1,0,-1,-2],
    [0,1,0,0],
    [0,0,1,0],
    [0,0,0,1]
])

p2 = np.array([
    [1,0,0,0],
    [-1,1,1,1],
    [0,0,1,1],
    [0,0,0,0]
])

P = np.matmul(p1,p2)
C = np.matmul(T,P)
print(C)

[[ 1  0  0  0]
 [ 0  1  0  0]
 [-1  1  0  0]]
