## Problem 3

In [22]:
import numpy as np

def norm_sq(v):
    return np.linalg.norm(v) ** 2

def proj(a,b):
    return (np.inner(a,b)/(np.linalg.norm(b)**2)) * b

v1 = np.array([1,0,1])
v2 = np.array([0,1,1])
v3 = np.array([1,3,3])

w1 = v1

w2 = v2 - proj(v2,w1)

w3 = v3 - proj(v3,w1) - proj(v3,w2)

w1 = w1 / np.linalg.norm(w1)
w2 = w2 / np.linalg.norm(w2)
w3 = w3 / np.linalg.norm(w3)

print(w1)
print(w2)
print(w3)

v = np.array([1,2,3])

s1 = np.inner(v,w1)
s2 = np.inner(v,w2)
s3 = np.inner(v,w3)

print(s1)
print(s2)
print(s3)

s1 * w1 + s2 * w2 + s3 * w3

[0.70710678 0.         0.70710678]
[-0.40824829  0.81649658  0.40824829]
[ 0.57735027  0.57735027 -0.57735027]
2.82842712474619
2.4494897427831788
2.220446049250313e-16


array([1., 2., 3.])