# Problem 1

In [16]:
import numpy as np

A = np.array([
    [1,2],
    [3,-1],
    [0,1],
    [5,7]
]
)

A_T = A.T
A_T

P1 = np.array([
    [1,0],
    [-2,1]
])

R1 = np.matmul(P1,A_T)

P2 = np.array([
    [1,3/7],
    [0,-1/7]
])
R2 = np.matmul(P2,R1)
R2

B = np.array([
    [0,0],
    [0,0],
    [1.0,0],
    [0,1.0]
    ])

B[0:2,0:2] = -1 * R2[:,2:4]

np.matmul(A_T,B[:,1])

array([0., 0.])

# Problem 4
## Part A
compute SVD of A and give the numerical result

In [26]:
A = np.array([
    [1,1,3],
    [2,3,8],
    [3,5,13],
    [1,-2,-3]
])


U,S,V_H = np.linalg.svd(A)

#create sigma matrix
Sigma = np.zeros((4,3))
Sigma[0,0] = S[0]
Sigma[1,1] = S[1]
Sigma[2,2] = S[2]

out_str = "U:\n{}\n\nSigma:\n{}\n\n V_H:\n{}".format(U,Sigma,V_H)

print(out_str)

U:
[[-0.18979384 -0.19913305  0.79293446  0.54367202]
 [-0.50526862 -0.14275606 -0.58233696  0.62065126]
 [-0.82074341 -0.08637907  0.15432321 -0.54323408]
 [ 0.18724897 -0.96566319 -0.09123018 -0.1552723 ]]

Sigma:
[[1.73584608e+01 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.91933276e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.03861641e-15]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]]

 V_H:
[[-0.20020855 -0.35624211 -0.91269277]
 [-0.89064576  0.45434006  0.01803437]
 [-0.40824829 -0.81649658  0.40824829]]


## Part B

In [30]:
#compute U1,Sigma1,and V1H

U_1 = U[:,0:2]
Sigma_1 = Sigma[0:2,0:2]
V_1_H = V_H[0:2,:]

out_str = "U_1:\n{}\n\nSigma_1:\n{}\n\n V_1_H:\n{}\n\n".format(U_1,Sigma_1,V_1_H)
print(out_str)

#solve for projection operator
P_A = U_1 @ U_1.T

#solve for pseudoinverse
pseudoinverse = V_1_H.T @ np.linalg.inv(Sigma_1) @ U_1.T

out_str = "P_A:\n{}\n\nPseudoinverse:\n{}".format(P_A,pseudoinverse)
print(out_str)

U_1:
[[-0.18979384 -0.19913305]
 [-0.50526862 -0.14275606]
 [-0.82074341 -0.08637907]
 [ 0.18724897 -0.96566319]]

Sigma_1:
[[17.35846081  0.        ]
 [ 0.          1.91933276]]

 V_1_H:
[[-0.20020855 -0.35624211 -0.91269277]
 [-0.89064576  0.45434006  0.01803437]]


P_A:
[[ 0.07567568  0.12432432  0.17297297  0.15675676]
 [ 0.12432432  0.27567568  0.42702703  0.04324324]
 [ 0.17297297  0.42702703  0.68108108 -0.07027027]
 [ 0.15675676  0.04324324 -0.07027027  0.96756757]]

Pseudoinverse:
[[ 0.09459459  0.07207207  0.04954955  0.44594595]
 [-0.04324324 -0.02342342 -0.0036036  -0.23243243]
 [ 0.00810811  0.02522523  0.04234234 -0.01891892]]


In [31]:
A @ pseudoinverse

array([[ 0.07567568,  0.12432432,  0.17297297,  0.15675676],
       [ 0.12432432,  0.27567568,  0.42702703,  0.04324324],
       [ 0.17297297,  0.42702703,  0.68108108, -0.07027027],
       [ 0.15675676,  0.04324324, -0.07027027,  0.96756757]])

## Part C

In [35]:
x = np.array([[1,2,3,4]]).T

#compute projection onto R(A)
P_R_A = P_A @ x

#compute projection onto orthogonal compliment of A
U_2 = U[:,2:4]
P_R_A_Ortho_compliment = U_2 @ U_2.T @ x

out_str = "Projection onto Range of A:\n{}\n\nProjection onto orthogonal compliment of A:\n{}".format(P_R_A,P_R_A_Ortho_compliment)
print(out_str)

Projection onto Range of A:
[[1.47027027]
 [2.12972973]
 [2.78918919]
 [3.9027027 ]]

Projection onto orthogonal compliment of A:
[[-0.47027027]
 [-0.12972973]
 [ 0.21081081]
 [ 0.0972973 ]]
