## Problem 5

In [7]:
import numpy as np

#define the basis for the subspaces
a = np.array([
    [1/np.sqrt(5),2/np.sqrt(5)]
]).T

b = np.array([
    [1,0]
]).T

#define the projection matricies
P_a = (a @ a.T)/np.power(np.linalg.norm(a),2)
P_b = (b @ b.T)/np.power(np.linalg.norm(a),2)

v_0 = 50 * b

#solve for the requested values
v_1 = P_a @ v_0
v_2 = P_b @ v_1
v_3 = P_a @ v_2
v_4 = P_b @ v_3

out_str = "V1:\n{}\n\nV2:\n{}\n\nV3\n{}\n\nV4:\n{}".format(v_1,v_2,v_3,v_4)
print(out_str)

V1:
[[10.]
 [20.]]

V2:
[[10.]
 [ 0.]]

V3
[[2.]
 [4.]]

V4:
[[2.]
 [0.]]
